# permissions for end users to view samplings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sampling-viewer-role
rules:
- apiGroups:
  - tuning.kubedl.io
  resources:
  - samplings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tuning.kubedl.io
  resources:
  - samplings/status
  verbs:
  - get
