# permissions for end users to edit utils.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: util-editor-role
rules:
- apiGroups:
  - tuning.kubedl.io
  resources:
  - utils
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tuning.kubedl.io
  resources:
  - utils/status
  verbs:
  - get
